### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by ReinforcedPanda** [uragirii/anYme-dl#2]
Unfortunately, have another index out of range error. Program does not crash, but episodes stop downloading after so many Abuse Protection waits. Can you take a peak? I was downloading Naruto Dubbed. It stopped on episode 48 as shown in log below.

EDIT: And now I think I know why. If I go to the website, they've added a daily limit.
> Daily page view limit exceeded. You were limited for opening high amount of pages from your network. Limit will be lifted after 24 hours.
> You have triggered abuse protection. Wait 60 seconds before continuing.

> Downloading Episode num : 48 | Total Available episodes : 220
Triggered Abuse Protection, waiting for 60 seconds
Again Triggered. Please close any browser window opening Animeheaven.eu site
Waiting for another 60 seconds
Again waiting..
Again waiting..
Again waiting..
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 49 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 50 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 51 | Total Available episodes : 220
Triggered Abuse Protection, waiting for 60 seconds
Again Triggered. Please close any browser window opening Animeheaven.eu site
Waiting for another 60 seconds
Again waiting..
Again waiting..
Again waiting..
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 52 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 53 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 54 | Total Available episodes : 220
Triggered Abuse Protection, waiting for 60 seconds
Again Triggered. Please close any browser window opening Animeheaven.eu site
Waiting for another 60 seconds
Again waiting..
Again waiting..
Again waiting..
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 55 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 56 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 57 | Total Available episodes : 220
Triggered Abuse Protection, waiting for 60 seconds
Again Triggered. Please close any browser window opening Animeheaven.eu site
Waiting for another 60 seconds
Again waiting..
Again waiting..
Again waiting..
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 58 | Total Available episodes : 220
Error Occured!! Downloading Stopped.
list index out of range
Downloading Episode num : 59 | Total Available episodes : 220
Error Occured!! Downloading Stopped.

**Comment by uragirii** [comment]
> Daily page view limit exceeded. You were limited for opening high amount of pages from your network. Limit will be lifted after 24 hours.

I can't think of anything to go around this. I mean if there is a daily limit then, it would be impossible to download large anime like Naruto, One piece in one go.
