### ISSUE TITLE
Episode list index off by 1

### ISSUE THREAD

**Issue by ReinforcedPanda** [uragirii/anYme-dl#3]
For example, download just episode 1 of Naruto Dubbed, or Cowboy Bebop dubbed, the script will actually download episode 2, not 1. I have to go back and rename a lot of episodes because of this...

**Comment by uragirii** [comment]
It was a silly mistake that crept in. I'm sorry. I've fixed it. Just check it.
@ReinforcedPanda I have a favor to ask you, can you email me `mldata.apoorv@gmail.com` and become my tester. Lately my commits have many such mistakes and I want someone to point them out before I push my code to GitHub.
It would be a great help.

**Comment by ReinforcedPanda** [comment]
I will email you later in the evening about the testing.

A bug probably introduced from fixing the index, now the script just doesn't download the first episode as shown below. I entered 1 - 20, and it starts on episode 2, but with that said, the episodes are correct now. Before the episode index was off, but not only that, when abuse protection was triggered, it would download the previous episode instead of the next episode. That seems to be fixed as well.

> Saving the episodes in the directory Naruto Dubbed
Enter the range/episode you want to download.

[ Enter '0' for downloading complete anime or twonumbers between 1 and 220 separated by '-' or just enter the episode number]
1-20
Downloading Episode num : 2 | Total Available episodes : 220

**Comment by uragirii** [comment]
I've added the fix. Hopefully this time it does not makes new errors . But please keep reporting.
Thanks
